### ISSUE TITLE
Загрузка изображения нужного размера без обработки

### ISSUE THREAD

**Issue by mr9d** [mr9d/acomics-crop#1]
Если пользователь загружает изображение, которое по ширине и высоте уже соответствует параметрам `data-target-width` и `data-target-height`, то обрабатывать его НЕ нужно.

Это нужно для анимированных картинок, которые делают некоторые авторы, так как анимания после обработки теряется. 

Считаем, что если автор уже сам подготовил изображение нужного размера, то можно его загружать как есть.

**Comment by DmitryDos** [comment]
За соответствие размеров мы принимает точное равенство или пропорциональное равенство, если например изображение имеет то же отношение сторон, как и в input'е мы его должны открыть или также пропустить обработку?

**Comment by mr9d** [comment]
> За соответствие размеров мы принимает точное равенство или пропорциональное равенство, если например изображение имеет то же отношение сторон, как и в input'е мы его должны открыть или также пропустить обработку?

Спасибо за вопрос! Только точное равенство.

**Comment by mr9d** [comment]
Сделано в https://github.com/mr9d/acomics-crop/pull/6
