### ISSUE TITLE
Проверка минимального размера изображения при загрузке

### ISSUE THREAD

**Issue by mr9d** [mr9d/acomics-crop#2]
При загрузке размеры изображения должно быть не меньше `data-target-width` и `data-target-height` по ширине и высоте, соответственно. Иначе результат кадрирования будет мыльным.

Если пользователь загружает не подходящее изображение, вывести предупреждение и не обрабатывать дальше.

**Comment by DmitryDos** [comment]
Есть какие-нибудь требования к предупреждению? Его лучше реализовать в виде временного всплывающего окна или можно использовать встроенный alert?

**Comment by mr9d** [comment]
> Есть какие-нибудь требования к предупреждению? Его лучше реализовать в виде временного всплывающего окна или можно использовать встроенный alert?

В первом приближении можно сделать просто alert.

**Comment by mr9d** [comment]
Сделано в https://github.com/mr9d/acomics-crop/pull/6
